# Настройки телеграм-бота.
telegram:
  bot_token: "" # токен бота.
  system_chats: # Список телеграм-чатов для системных уведомлений.
    - ""
    - ""
  admin_chats: # Список телеграм-чатов для админов.
    - ""
    - ""
  events_chats: # Список телеграм-чатов для уведомлений администрации.
    - ""
    - ""
  editor_chats: # Список телеграм-чатов для уведомлений редакторов.
    - ""
    - ""
# Данные подключения к брокеру сообщений RabbitMQ.
rabbitmq:
  username: ""
  password: ""
  host: ""
  port: ""
