# Настройки телеграм-бота.
telegram:
  bot_token: "" # токен бота.
  system_chats: # Список телеграм-чатов для системных уведомлений.
    - ""
    - ""
  admin_chats: # Список телеграм-чатов для админов.
    - ""
    - ""
  events_chats: # Список телеграм-чатов для уведомлений администрации.
    - ""
    - ""
# Данные подключения к брокеру сообщений RabbitMQ.
rabbitmq:
  username: "guest"
  password: "guest"
  host: "127.0.0.1"
  port: "5672"
